### ISSUE TITLE
Add new function for Encoder taking an ObjectTransmissionInformation 

### ISSUE THREAD

**Issue by evq** [cberner/raptorq#11]
Hey there!

I'm working on an application that blends RaptorQ and STROBE for efficient, secure transmission of files. In this combination it is ideal if the config can be created and sent to the other party first - before the final data to be encoded is ready.

Are you open to having a `Encoder::new` that takes the config and data?

**Comment by cberner** [comment]
Sure, that sounds reasonable. Just send a PR

**Comment by cberner** [comment]
Closing, but feel free to send a PR!
