### ISSUE TITLE
How to run the files in examples folder

### ISSUE THREAD

**Issue by lipeijie10** [cberner/raptorq#111]
Hello Christopher,

Sorry for the naive questions. I'm new to Rust. When I run `rustc main.rs` or `python3 main.py` in example folder, it gives me error like library not found. Can you give us more instruction how to play with the `main.rs` and `main.py` examples in this project?

Thanks,
PJ

**Comment by cberner** [comment]
Yes, you need to use Cargo. See here: https://doc.rust-lang.org/cargo/commands/cargo-build.html

Like `cargo build --examples`
