### ISSUE TITLE
Confusion of performance difference between encode_benchmarks.rs and main.rs

### ISSUE THREAD

**Issue by lipeijie10** [cberner/raptorq#113]
Hi Christopher,

I modified the main.rs to get the encoding time for 100 symbols and each symbol in 1280 bytes as in your benchmarks. I got a time is 0.078s for encoding.  
```rust
use rand::seq::SliceRandom;
use rand::Rng;
use raptorq::{Decoder, Encoder, EncodingPacket};
use std::time::Instant;

fn main() {
    // Generate some random data to send
    let mut data: Vec<u8> = vec![0; 100 * 1280]; // Change to 100 symbols, each is 1280 bytes
    for i in 0..data.len() {
        data[i] = rand::thread_rng().gen();
    }
    let now = Instant::now();
    let encoder = Encoder::with_defaults(&data, 1280); // To 1280 bytes

    // Perform the encoding, and serialize to Vec<u8> for transmission
    let mut packets: Vec<Vec<u8>> = encoder
        .get_encoded_packets(15)
        .iter()
        .map(|packet| packet.serialize())
        .collect();
    let elapsed = now.elapsed();
    let elapsed = elapsed.as_secs() as f64 + elapsed.subsec_millis() as f64 * 0.001;
    println!("Total time consumed in seconds: {}", elapsed);
}
```
However, from your bench result, the time is 0.393s / ((127 * 1024 * 1024 Bytes) / (100 * 1280)) = 0.000378s.
```
Symbol size: 1280 bytes (without pre-built plan)
...
symbol count = 100, encoded 127 MB in 0.393secs, throughput: 2604.2Mbit/s
...
```
There are around 200x speed difference. I believe there is something I'm missing between the usages in main.rs and encode_benchmarks.rs. Can you help me understand why it is?

Thanks,
PJ

**Comment by cberner** [comment]
With only ~128k of data, you may be running into overhead. Try a larger amount of data, like 100MB, and see how that performs. Also did you try running the benchmark on your own computer? If your CPU is slower than the one I used, the encoding will be slower too

**Comment by lipeijie10** [comment]
My CPU is 9700K, which shouldn't be a bottleneck. To set a large amout of data, is it to set data vector to a larger one?
For example from ~128KB to 128MB
`let mut data: Vec<u8> = vec![0; 1024 *1024 * 128]; `
In my side, it leads to running forever.

**Comment by cberner** [comment]
Did you build in release mode? i.e. `cargo --release ...`

**Comment by lipeijie10** [comment]
Aha, you give me the right direction! The release mode and debug mode has a 200X speed difference. Thank you!

**Comment by lipeijie10** [comment]
In this mode, the

**Comment by cberner** [comment]
Yes

**Comment by lipeijie10** [comment]
Great, thank you!
