### ISSUE TITLE
Decode encoded symbols with pre-built plan

### ISSUE THREAD

**Issue by lipeijie10** [cberner/raptorq#115]
Hello Christoper,

Sorry for asking dumb questions again and again. How can I determine the decoder config if the data is encoded with pre-built plan encoder like in the encode_benchmark.rs? I didn't find the decoder constructor with a plan.

Thank you again,
PJ

**Comment by cberner** [comment]
You'll need to construct an `ObjectTransmissionInformation` object. You can use the `with_defaults` method
