### ISSUE TITLE
Potential Qualcomm legal liability?

### ISSUE THREAD

**Issue by jackloomen** [cberner/raptorq#116]
There may be a legal liability when using RaptorQ for commercial purposes - Qualcomm can sue you.
Hopefully I'm wrong and someone can point that out.

This is Qualcomm's IPR statement: https://datatracker.ietf.org/ipr/2554/

Relevant section:

> If the technology in RFC6330 “RaptorQ Forward Error Correction Scheme for Object Delivery” is included in a standards track or experimental document adopted by the IETF, and any claim of any patent issued from the above mentioned patents, patent applications or corresponding patents and patent applications is required for the implementation of any device that (a) fully implements such adopted standards track or experimental document; and (b) **does not implement any wireless wide-area standard**, Qualcomm will not assert any such claim against any party for making, using, selling, importing or offering for sale such device but solely with respect to the implementation of such adopted standards track or experimental document, provided, however that Qualcomm retains the right to assert its patent(s) issued on the above mentioned application or corresponding patent applications (including the right to claim past royalties) against any party that asserts a patent it owns or controls (either directly or indirectly) against any products of Qualcomm or any products of any of Qualcomm's Affiliates either alone or in combination with other products; and **Qualcomm retains the right to assert its patents or application(s) against any product or portion thereof that does not fully implement the IETF standards track or experimental document**.

Does this implementation "fully implement the IETF standards track or experimental document"?

Oh if you are a corporate entity this IPR is probably cancer, you are giving Qualcomm license to infringe on any of your patents and going after them means they go after you. But I'm more interested in how this affects small businesses.

**Comment by cberner** [comment]
Unfortunately yes, there are patents that apply to RaptorQ. If you plan to use it for commercial purposes, I recommend you consult a lawyer.
You will need to determine for yourself whether this implementation fully implements the IETF standard. I can make no assertions about whether it does.
