### ISSUE TITLE
Implementing Interleaving ?

### ISSUE THREAD

**Issue by jblestang** [cberner/raptorq#119]
Any plane to add data [interleaving ](https://www.qualcomm.com/media/documents/files/broadcast-delivery-of-multimedia-content-to-mobile-users.pdf) to handle loss of burst of packets like in figure 9 of Qualcomm paper

**Comment by cberner** [comment]
If I understand correctly interleaving means running the encoder with `subblocks > 1`. That's already supported: https://github.com/cberner/raptorq/blob/4bf46ec16bde6352ee7df96fcba5f7ffeac4b0ad/src/encoder.rs#L205-L226

Please re-open, if it means something else
