### ISSUE TITLE
benchmark(symbol_size, 0.50) get panic while symbol count is set to 10

### ISSUE THREAD

**Issue by ycopy** [cberner/raptorq#120]
Hi Cberner,

benchmark(symbol_size, 0.50) get panic issue, the detailed panic info as below:

thread 'main' panicked at 'index out of bounds: the len is 16 but the index is 16', src\arraymap.rs:192:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Do you have any clue on this ?

**Comment by cberner** [comment]
Fixed. Thanks for the report!
