### ISSUE TITLE
Making systematic_constans API public

### ISSUE THREAD

**Issue by andreiltd** [cberner/raptorq#131]
Hey, I'm working on GStreamer plugin for RaptorQ RTP FEC using this crate. One of the requirement defined in relevant RFCs is to provide information about `kmax` or `K'` by the encoder. I can see there is a function to obtain that but it is currently private:

```rust
systematic_constants::extended_source_block_symbols
``` 

Would you be willing to make that public? Of course I can provide a PR.

Thanks for all your amazing work!

**Comment by cberner** [comment]
Ya, for sure. I see that I already made that conditionally public for my benchmarking scripts, so seems reasonable to just make it completely public!

Need any of the other systematic constants?
