### ISSUE TITLE
Rabin IDA

### ISSUE THREAD

**Issue by dirvine** [cberner/raptorq#135]
Hi, great work here. Fascinating too. 
I have a use case for a 5 of 7 IDA for data up to 1Mb. i.e. end up with 7 pieces that 5 are enough to recreate the data. 

I was pulling together a basic Rabin IDA for this, but looking quickly here I wonder if it's possible with the config options to actually make that happen. (what options should I set)

2nd question is, should I use this crate for that?

**Comment by cberner** [comment]
I'm not familiar with Rabin, but I suspect you want Reed Solomon and not RaptorQ for that. Reed Solomon guarantees that 5 of 7 are sufficient to recreate the message, whereas RaptorQ does not (it only provides a probabilistic guarantee).

So no, I don't think this is the right create

**Comment by dirvine** [comment]
Thanks for the info, much appreciated.
