### ISSUE TITLE
Taking too long to encode

### ISSUE THREAD

**Issue by vinay10949** [cberner/raptorq#144]
unencoded_packet_list size is 1020076 bytes ,
PAYLOAD_SIZE=1280bytes
`let encoder = Encoder::with_defaults(unencoded_packet_list, (PAYLOAD_SIZE) as u16);;` 
Code gets stuck when i run this .

**Comment by cavemanloverboy** [comment]
I am running into the same issue. More generally, it seems this implementation is slower than Reed-Solomon (comparing to `reed_solomon_erasure` crate) for both small and large data sizes.

**Comment by cavemanloverboy** [comment]
I ran into the same issue. Are you running in release mode?

**Comment by vinay10949** [comment]
@cavemanloverboy  Yes

**Comment by cavemanloverboy** [comment]
I just used this library with an 800 MB file and had the appearance of hanging (waited 5 min) on debug, but got <1s encoding on release mode.

**Comment by cberner** [comment]
@vinay10949 are you able to reproduce this issue by adjusting the settings in https://github.com/cberner/raptorq/blob/master/benches/encode_benchmark.rs ? I can take a look if so

**Comment by vinay10949** [comment]
@cberner  it takes less than 56ms in release mode, but it takes too long for debug mode @cavemanloverboy

**Comment by cberner** [comment]
Ah, that's not a bug. You should always use release mode if you care about performance
