### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by emiliopaolini** [cberner/raptorq#159]
Hi all,

i am trying to use the library with python bindings. However i am finding some issues and I cannot find a documentation in which the methods available are described. Is there one? Even if it is for rust, it is good!

**Comment by cberner** [comment]
https://docs.rs/raptorq/latest/raptorq/

There is some documentation for the Rust lib there

**Comment by emiliopaolini** [comment]
Thank you for the information. I have another concerns: when i build the encoder, I call get_encoded_packets(x), what is x? From the doc, i can see it says: repair_packets_per_block, but what does it actually mean? Thanks!

**Comment by cberner** [comment]
It's the number of unique repair packets that you will get
