### ISSUE TITLE
Information on the encoded packets

### ISSUE THREAD

**Issue by emiliopaolini** [cberner/raptorq#161]
Hello, as the title mentions, I was wondering about which part of the encoded packets contain the source symbol indices. 
More in details: I noticed that when Encoder and Decoder exchange packets, no information on the source symbols used to create the encoded packets are added (like the index of them). So I guess these information is added in the encoded packet, is it right? And if so, in which part of the encoded is it contained? Thanks.

**Comment by cberner** [comment]
It's in the payload id
