### ISSUE TITLE
With the decoder, is it possible to return any decoded data, even if channel loss is too high and not enough packets are available at the decoder?

### ISSUE THREAD

**Issue by mr10abb** [cberner/raptorq#168]
My apologies for using the issue system to ask this question, I couldn't see any other way to get in contact.

For context, I am using your Python package to encode an RTP video stream in _X_ms chunks. The data is then sent via multicast to multiple end users via a lossy WiFi channel.
At each decoder, I would like to be able to retrieve any packets that have been successfully decoded.
Currently I am using:
```python
for packet in received_packets:
    result = decoder.decode(packet)
    if result is not None:
        break
``` 
As per your Python example.
This however only returns the original data if it has been 100% successfully decoded.
Is there a way to stop the decoding process after I have run out of received packets (i.e., the loss was too high and `result` is still `None`?), and then return any data that has been decoded successfully? Or even return the best guess?
 
In my example, I am simply concatenating the RTP packets into the _X_ms chunks which are then encoded, so after decoding, I would then split the chunk back into RTP packets, and check their CRCs to determine if they should be forwarded onto the video application.

Thank you for taking the time to read this, and thank you for developing this project!

The work am I undertaking is part of my research into SDN control, and I intended to make it open source alongside publications.

Kind regards,
Matt, University of Hertfordshire, m.robinson20 AT herts.ac.uk

**Comment by cberner** [comment]
iirc, all the initial blocks contain the original data, only the repair
blocks contain parity data. So you can take the data from the initial
source blocks and reassembly it. Unfortunately, that's about all the
guidance I can provide. I've never tried doing that and am no longer
actively developing this project. But I recall that the spec is quite clear
on how to construct the initial source packets
