### ISSUE TITLE
Rust API guidelines

### ISSUE THREAD

**Issue by ckaran** [cberner/raptorq#23]
Are you open to implementing the recommendations of the [Rust API guidelines?](https://rust-lang.github.io/api-guidelines) I noticed that you're rolling your own serialization rather than using [serde](https://crates.io/crates/serde), and there are a number of standard traits that aren't implemented on your types (which makes it impossible for others to implement those traits due to Rust's [orphan rules](https://github.com/Ixrec/rust-orphan-rules))

I'm willing to start doing PRs to implement some of these (e.g. serde, `Clone`, etc.), but wanted to know if you're open to them.

**Comment by cberner** [comment]
Yep, I'm happy to merge PRs to implement those. Thanks for the pointer to the guidelines too. I wasn't aware of those.

**Comment by ckaran** [comment]
OK, I'll start sending you PRs as I complete things.  Be warned that some of the PRs are breaking changes; e.g., moving to using serde for serialization will mean that eventually you won't have your own serialization code in place.  I'll make sure that you're aware of those via the commit messages (I follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard).
