### ISSUE TITLE
CPython wrapper

### ISSUE THREAD

**Issue by felixschorer** [cberner/raptorq#26]
I have written a small wrapper to compile the library to a native CPython module.
Currently, it only features the high level Encoder/Decoder API.
The code is part of [that repository](https://github.com/felixschorer/cmb-protocol/tree/master/raptorq).

Shall I open a PR to integrate the code into this repository?

**Comment by cberner** [comment]
I'm happy to integrate it. However, I'm not sure how to. It looks like your wrapper requires changing the crate-type to "cdylib". Is there a way to make that conditional on a feature flag?

**Comment by felixschorer** [comment]
I would have added a second crate (i.e. `python/cargo.toml`) which references the main crate.

**Comment by cberner** [comment]
Ah, that makes sense. Sure, I'd be happy to merge a PR that integrates it as another crate
