### ISSUE TITLE
Remove ad-hoc serialization code

### ISSUE THREAD

**Issue by ckaran** [cberner/raptorq#28]
PR #27 ensures that most of the structs in the crate have `serde::{Serialize, Deserialize}` implemented on them.  That means that any ad-hoc serialization code (such as  `ObjectTransmissionInformation::{serialize(), deserialize()}`) are no longer necessary, and may actually be detrimental in the long run.  Although it will be a breaking change requiring a major version bump, it may be a good idea to remove the ad-hoc code.

**Comment by cberner** [comment]
Going to close this. Those methods are necessary because they use the RFC6330 serialization format
