### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by lucab** [cberner/raptorq#3]
Sorry for the silly ticket, but I'm having a hard time trying to figure out how the API of this crate is supposed to be consumed.

I'm particular, I'm failing to get a structured view to answer to the following:
 * why is `EncodingPacket` private?
 * how can I get encoded bytes out of the Encoder?
 * how can I decode a slice of bytes (e.g. from a file)?
 * can encoding/decoding work in a streaming way or do they need all input data upfront?

**Comment by cberner** [comment]
* Sorry about that! I'm releasing a new version `0.7.1` that makes it public. This library is still very much a work in progress :)
* EncodingPacket is now public :)
* You'll need to convert them to EncodingPacket and pass to the decoder
* No, I don't think that's possible to implement with RaptorQ
