### ISSUE TITLE
Next release to crates.io?

### ISSUE THREAD

**Issue by ckaran** [cberner/raptorq#34]
Do you have a plan for when you're going to publish your next release to crates.io?  I'm currently setting my cargo.toml to point to this repository's master branch, but that's kind of hacky...

**Comment by cberner** [comment]
I'm planning to do one no later than the end of the month. I'm working on a bunch of performance optimizations for encoding large numbers of symbols. I'd like to include that work, as it's already giving a ~2x speedup and I expect to get a bit more

**Comment by cberner** [comment]
Released 1.1.0

**Comment by ckaran** [comment]
Thank you!
