### ISSUE TITLE
Support subblocks?

### ISSUE THREAD

**Issue by ekmett** [cberner/raptorq#44]
What would be needed to support subblocks?

I went to use this for a data transmission application, and ran afoul of the buried assert in the encoder, but as I have no idea what caused that assertion to be buried there, I'm somewhat leery of playing around with it without context.

**Comment by ekmett** [comment]
My first knee-jerk response was that I could just create an `Encoder` with # of subblocks forced to 1 or something, but the only exposed constructor for `Encoder` is `with_defaults`, so there is no parameter within my control other than the initial data size that will guide whether the library tries to use them.

**Comment by ekmett** [comment]
I'm guessing the issue has something to do with the fact that after sub-blocks are introduced symbols aren't necessarily contiguous storage?

**Comment by cberner** [comment]
I think it's relatively straight forward. The section on sub-block partitioning and recovery just needs to be implemented (https://tools.ietf.org/html/rfc6330#section-4.4.1.2). I'm happy to merge a PR, if you want to implement it. Otherwise, I'll probably get to it in the next week or so

**Comment by cberner** [comment]
This PR will allow you to configure the memory usage, and hence the number of sub-blocks created. Depending on the amount of data you're encoding, setting it higher may be a workaround for the moment: https://github.com/cberner/raptorq/pull/48

**Comment by cberner** [comment]
Just merged support for this. Can you give it a try?

**Comment by ekmett** [comment]
Will do!
