### ISSUE TITLE
Panic With Large Datasets

### ISSUE THREAD

**Issue by dmarchant** [cberner/raptorq#58]
Thanks for making this awesome library! I am seeing a panic when I use it with large data sets on both Windows and Linux. If you modify line 7 on `raptorq/examples/main.rs` to be `let mut data: Vec<u8> = vec![0; 100_000_000];` and then run it using `cargo run --release --example main` it will panic with the error below. Do you know of a workaround for this error?
```
cargo run --release --example main
    Finished release [optimized + debuginfo] target(s) in 0.08s
     Running `target\release\examples\main.exe`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src\decoder.rs:230:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\examples\main.exe` (exit code: 101)
```

**Comment by cberner** [comment]
Just merged a fix. Thanks for reporting this!
