### ISSUE TITLE
Question from arraymap.rs

### ISSUE THREAD

**Issue by ycopy** [cberner/raptorq#60]
Hi Cberner, This is the best RQ implementation I've ever seen.
I'm learning your code these days, I was confused by the following code, I’d appreciate if you could help. 
1)	file (arraymap.rs), (the line starting from line 215 below) 
    pub fn with_capacity(start_key: usize, end_key: usize) -> U32VecMap {
        U32VecMap {
            offset: start_key,
            elements: vec![0; end_key],
        }
    }

In my understanding of your intention, the elements should be initialed by 
vec![0;end_key-start_key]
2)	file arraymap.rs, the line starting from line 234
    pub fn swap(&mut self, key: usize, other_key: usize) {
        self.elements.swap(key, other_key);
    }

If the offset is not initialed from 0, would it be ok ?
Thanks in advance

**Comment by cberner** [comment]
Thanks for finding those! You're right, about both. Neither causes a bug in the encoder, because swap() is never used, and the allocating that extra memory is safe (if wasteful). I have a PR to fix them: https://github.com/cberner/raptorq/pull/61
