### ISSUE TITLE
[question]About the recovery strategies

### ISSUE THREAD

**Issue by ycopy** [cberner/raptorq#62]
Hi Cberner, 

	It seems that your implementation of recovery strategies is for devices that have enough RAM, (please correct me if I am wrong).
	According to RFC6330 4.4.3 's last paragraph, There is an alternative approach for RAM limited devices, what do you think of it ? 

	Have a nice day. thanks in advance.

**Comment by cberner** [comment]
Yes, that's how `Encoder` works, since I didn't want it to manage disk storage. If you have an environment with limited RAM, you probably want to use the `SourceBlockDecoder` interface. You can use that to decode a single block at a time

**Comment by ycopy** [comment]
I get the idea, thank you. 

BTW, I get a little performance up by removing the get_row_iter.clone operation in firstPhaseRowSelectionStats::first_phase_swap_columns_substep, It seems safe to remove it, But I'm not very sure.
