### ISSUE TITLE
assert!((symbols_required as u32) < MAX_SOURCE_SYMBOLS_PER_BLOCK);

### ISSUE THREAD

**Issue by Intrepd** [cberner/raptorq#63]
In ObjectTransmissionInformation (base.rs:120)

Since

`// See section 4.4.1.2. "These parameters MUST be set so that ceil(ceil(F/T)/Z) <= K'_max."`

should this assert instead be less than or equal?

`assert!((symbols_required as u32) <= MAX_SOURCE_SYMBOLS_PER_BLOCK);`

Thanks--very nice work btw.

**Comment by cberner** [comment]
Ah yes, you're right. Thanks for finding that!
