### ISSUE TITLE
cargo bench fails to build

### ISSUE THREAD

**Issue by ChaiTRex** [cberner/raptorq#69]
With the current `HEAD`, `cargo bench` fails to build:

    $ git log -n 1
    commit 95b6b5ae9100d2af9518f76450dba93bcad79902 (HEAD -> master, github/master, github/HEAD)
    Author: Christopher Berner <christopherberner@gmail.com>
    Date:   Sat Aug 29 22:35:08 2020 -0700
    
        Make serde support optional
    
    $ git status
    On branch master
    Your branch is up to date with 'github/master'.
    
    nothing to commit, working tree clean
    
    $ cargo bench
       Compiling autocfg v1.0.1
       Compiling libc v0.2.77
<details><summary>⋮</summary>

       Compiling maybe-uninit v2.0.0
       Compiling cfg-if v0.1.10
       Compiling lazy_static v1.4.0
       Compiling serde v1.0.116
       Compiling semver-parser v0.7.0
       Compiling memchr v2.3.3
       Compiling byteorder v1.3.4
       Compiling proc-macro2 v1.0.21
       Compiling ryu v1.0.5
       Compiling unicode-xid v0.2.1
       Compiling scopeguard v1.1.0
       Compiling rayon-core v1.8.0
       Compiling getrandom v0.1.15
       Compiling either v1.6.0
       Compiling bitflags v1.2.1
       Compiling serde_json v1.0.57
       Compiling syn v1.0.40
       Compiling itoa v0.4.6
       Compiling serde_derive v1.0.116
       Compiling unicode-width v0.1.8
       Compiling hamming v0.1.3
       Compiling primal-estimate v0.2.1
       Compiling half v1.6.0
       Compiling same-file v1.0.6
       Compiling regex-syntax v0.6.18
       Compiling ppv-lite86 v0.2.9
       Compiling oorandom v11.1.2
       Compiling raptorq v1.4.2 (/home/chai/src/raptorq)
       Compiling semver v0.9.0
       Compiling crossbeam-utils v0.7.2
       Compiling memoffset v0.5.5
       Compiling num-traits v0.2.12
       Compiling crossbeam-epoch v0.8.2
       Compiling num-integer v0.1.43
       Compiling rayon v1.4.0
       Compiling itertools v0.9.0
       Compiling textwrap v0.11.0
       Compiling primal-bit v0.2.4
       Compiling walkdir v2.3.1
       Compiling rustc_version v0.2.3
       Compiling regex v1.3.9
       Compiling smallvec v0.6.13
       Compiling num_cpus v1.13.0
       Compiling atty v0.2.14
       Compiling csv-core v0.1.10
       Compiling cast v0.2.3
       Compiling serde_cbor v0.11.1
       Compiling quote v1.0.7
       Compiling regex-automata v0.1.9
       Compiling clap v2.33.3
       Compiling primal-sieve v0.2.9
       Compiling threadpool v1.8.1
       Compiling rand_core v0.5.1
       Compiling crossbeam-channel v0.4.4
       Compiling plotters v0.2.15
       Compiling bstr v0.2.13
       Compiling tinytemplate v1.1.0
       Compiling rand_chacha v0.2.2
       Compiling crossbeam-deque v0.7.3
       Compiling primal-check v0.2.3
       Compiling csv v1.1.3
       Compiling rand v0.7.3
       Compiling criterion-plot v0.4.3
</details>

       Compiling primal v0.2.3
       Compiling criterion v0.3.3
    error[E0432]: unresolved import `raptorq::generate_constraint_matrix`
     --> benches/matrix_sparsity.rs:1:5
      |
    1 | use raptorq::generate_constraint_matrix;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `generate_constraint_matrix` in the root
    
    error[E0432]: unresolved import `raptorq::IntermediateSymbolDecoder`
     --> benches/matrix_sparsity.rs:2:5
      |
    2 | use raptorq::IntermediateSymbolDecoder;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `IntermediateSymbolDecoder` in the root
    
    error[E0432]: unresolved import `raptorq::Octet`
     --> benches/matrix_sparsity.rs:3:5
      |
    3 | use raptorq::Octet;
      |     ^^^^^^^^^-----
      |     |        |
      |     |        help: a similar name exists in the module (notice the capitalization): `octet`
      |     no `Octet` in the root
    
    error[E0432]: unresolved import `raptorq::Symbol`
     --> benches/matrix_sparsity.rs:4:5
      |
    4 | use raptorq::Symbol;
      |     ^^^^^^^^^------
      |     |        |
      |     |        help: a similar name exists in the module (notice the capitalization): `symbol`
      |     no `Symbol` in the root
    
    error[E0432]: unresolved imports `raptorq::extended_source_block_symbols`, `raptorq::BinaryMatrix`, `raptorq::SparseBinaryMatrix`
     --> benches/matrix_sparsity.rs:5:15
      |
    5 | use raptorq::{extended_source_block_symbols, BinaryMatrix, SparseBinaryMatrix};
      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `SparseBinaryMatrix` in the root
      |               |                              |
      |               |                              no `BinaryMatrix` in the root
      |               no `extended_source_block_symbols` in the root
    
    error[E0432]: unresolved import `raptorq::Symbol`
      --> benches/codec_benchmark.rs:10:5
       |
    10 | use raptorq::Symbol;
       |     ^^^^^^^^^------
       |     |        |
       |     |        help: a similar name exists in the module (notice the capitalization): `symbol`
       |     no `Symbol` in the root
    
    error[E0432]: unresolved import `raptorq::Octet`
      --> benches/codec_benchmark.rs:11:46
       |
    11 | use raptorq::{ObjectTransmissionInformation, Octet};
       |                                              ^^^^^
       |                                              |
       |                                              no `Octet` in the root
       |                                              help: a similar name exists in the module (notice the capitalization): `octet`
    
    error: aborting due to 5 previous errors

    For more information about this error, try `rustc --explain E0432`.
    error: could not compile `raptorq`.

    To learn more, run the command again with --verbose.
    warning: build failed, waiting for other jobs to finish...
    error: aborting due to 2 previous errors
    
    For more information about this error, try `rustc --explain E0432`.
    error: build failed

**Comment by cberner** [comment]
You need to enable the `--features benchmarking` flag, because the benchmarks require some internal APIs. You can use the Makefile `make bench` for easy of use
