### ISSUE TITLE
Encoding very large files

### ISSUE THREAD

**Issue by pgrinaway** [cberner/raptorq#71]
Are there any plans to support encoding a file too large to fit into memory, without simply encoding pieces separately?  If not, is there an idea about how straightforward that would be to implement?

**Comment by cberner** [comment]
Ya, I've thought about it, and I don't think it's that hard. Basically just need to implement another version of `SourceBlockEncoder::with_encoding_plan2()` that takes a `File` instead of a `&[u8]`. The only tricky part is deciding how to specify the output: should it save the intermediate symbols to disk, or only a fixed number of repair symbols...etc? 

Can you tell me more about your use case, and what API would be easiest to use for you?

**Comment by pgrinaway** [comment]
Sure. Basically, we're trying to archive large (100GB+) files remotely and insure against some amount of adversarial corruption (which is partly why we want to encode an entire file together, and not as separate blocks). We aren't terribly concerned about latency; we're mostly trying to ensure that it is feasible to encode on a reasonably well-equipped machine.

I think as for API, we just want to be able to specify the number of repair symbols once (since the file will be archived after encoding and encryption).

**Comment by cberner** [comment]
Got it. That sounds pretty straightforward to build on top of this library. Take a look at `Encoder`, you should be able to implement your own which encodes one block at a time using a `SourceBlockEncoder`. That way you'll only need enough memory to encode a single block. Which is a few GB at most, iirc.

**Comment by pgrinaway** [comment]
Great, thanks!

**Comment by pgrinaway** [comment]
Actually, one question: if I take the approach above, must the blocks be decoded individually in the same manner? I know that the memory limitation would prevent that, but I am wondering whether the encoded data in each block is independent of the others. If it is, then an adversary can delete an entire block's worth of encoded data, causing it to be lost.

**Comment by cberner** [comment]
Yes, they will be independent. That's a limitation of the RFC. You won't be able to have 100GB encoded in a single piece. Each block can be fairly large (up to ~4GB, iirc)
