### ISSUE TITLE
Optimize performance on ARM

### ISSUE THREAD

**Issue by cberner** [cberner/raptorq#72]
SIMD functions for ARM need to be implemented

**Comment by sleepybishop** [comment]
you are more than welcome to use my oblas routines as reference, they are MIT licensed.

https://github.com/sleepybishop/oblas/blob/master/oblas_neon.c

i think only `oaxpy` and `oaddrow` are relevant to you.

i have yet to implement a neon version to populate a gf256 row from a gf2 row and instead rely on kernighan's trick but it's on my todo list.

**Comment by cberner** [comment]
Cool, thanks for the pointer!

**Comment by sleepybishop** [comment]
I spent some time playing around with https://github.com/DLTcollab/sse2neon, I thought it might be useful as another references to port your existing SIMD code to ARM.

**Comment by cberner** [comment]
Thanks! That looks useful.
